gitops
 - Understanding GitOps Architecture and Tooling

command line for developers
 - common linux shell commands
 - git command line
 - github cli, azure cli

yaml
 - what is yaml
 - features of yaml
 - yaml syntax

github actions
 - Core Concepts of a GitHub Action
 - Continuous Integration with GitHub Actions
 - Approval Workflow, Branch Protections, and Marketplace Actions

azure for developers
 -  Web apps, Azure Functions,Storage Accounts, API Management, API Gateway, Service Bus, Azure



Wniosek w cedig o zmiane na ryczalt Asia

1. Co zostało wykonane
2. 


Chciałbym podsumować koszty jakie poniosłem w trakcie rozwiązywania problemu z ogrzewaniem.
Nie byłem w stanie korzystać z mieszkania od poczatku okresu grzewczego. Z powodu bagatelizowania problemu przez Panstwa,
1. Mieszkanie było wykończone i gotowe do wprowadzenia, jednak temperatura 14-16 stopni uniemożliwiałą mieszkanie.
Przez cały ten okres, opłacałem czynsz i rachunki za ogrzewanie. 
2. Na początku grudnia na własną rękę próbowałem zlokalizować przyczynę problemu. Prosiłem o pomoc hydrualika,
3. Kolejna próbą była wymiana głowić termostatycznych w grzejnikach dekoracyjnych. Sugerowane rozwiązanie przez konserwatora, przedstawione później przez dewelopera.

W załączniku przesyłam rachunki i wszystkie dokumenty potwierdzające te działania.


name: Build Next.js web application
on: push
jobs:
build-project:
  name: Build Project
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Install NPM dependencies
    run: npm install
  - name: Build project assets
    run: npm run build
  - name: Upload static site
    uses: actions/upload-artifact@v2
    with:
      name: static-site
      path: .next/

release-project:
  name: Release Project
  runs-on: ubuntu-latest
  needs: build-project
  steps:
  - name: Download site content
    uses: actions/download-artifact@v2
    with:
      name: site-build
  - name: View content
    run: ls -R
  - name: Create GitHub release
    id: create-new-release
    uses: actions/create-release@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      tag_name: ${{ github.run_number }}
      release_name: Release ${{ github.run_number }}
  - name: Archive site content
    uses: thedoctor0/zip-release@master
    with:
      filename: site.zip
  - name: Upload release asset
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ steps.create-new-release.outputs.upload_url }}
      asset_path: ./site.zip
      asset_name: site-v${{ github.run_number }}.zip
      asset_content_type: application/zip
